### ISSUE TITLE
Shouldn't Domain.Case take a neutral argument?

### ISSUE THREAD

**Issue by minad** [ollef/sixty#6]
https://github.com/ollef/sixty/blob/7294718c1287ab0d5d28bd298ad4b70e76d6366b/src/Core/Domain.hs#L38
Domain.Case is defined as a Head, which takes a Value argument. If case expressions are fully covering, the scrutinee of the Case should always be a neutral. Then neutral heads would only be variables/metas, spines would either be blocked applications or blocked case expressions.

In the "Simply easy!" paper by Löh et al, they introduce a NatElim. Correspondingly they add a NNatElim to the neutrals, which takes a neutral as argument.

**Comment by ollef** [comment]
Yeah, the idiomatic place to add `Case` would be as an eliminator alongside applications in the spine of a `Neutral`. I have [an old branch](https://github.com/ollef/sixty/compare/case-elimination) where I try out something like that, but I found it to be cumbersome to implement e.g. unification with it, so I gave up on it.

With the current implementation, the scrutinee needs to be a `Value` to be able to represent case-of-case.

I might revisit that old branch at some point though, because it seems like the right thing to do.

**Comment by ollef** [comment]
This started bugging me, so I went and fixed it.

The problem I had with it earlier is that there are a few cases in the unifier that apply only when we have a meta applied to a bunch of arguments (i.e. not mixed with cases), so I made sure that checking if a neutral term is on that form is constant time by using a slightly more involved (maybe even clever?) representation of eliminations than a (reverse) list.

**Comment by minad** [comment]
Cool! Btw, how do you solve the index unification issue of inductive families? In your core language, are the indices introducing implicit coercions and the impossible branches are just missing? Or do you produce no-confusion terms etc during elaboration which are then present in the core syntax? See also the discussion in https://github.com/AndrasKovacs/elaboration-zoo/issues/25

**Comment by ollef** [comment]
The former, but I'd like to investigate if there's a better way to do it.
